#!/usr/bin/php
<?php

chdir(dirname(__FILE__));

shell_exec('rm -rf ./public/');
shell_exec('mkdir ./public');
shell_exec('cp -r ./src/* ./public/');
mkdir('./public/_assets/r4');
shell_exec('cp -r ./modules/r4/php ./public/_assets/r4/');
shell_exec('chown -R www-data. ./public');

require 'utils/templater.php';

require 'utils/packer.php';